#!/usr/bin/python3
import sys

if len(sys.argv) <= 1:
    seq = input("Enter sequence: ")
else:
    seq = sys.argv[-1]
    
complement = {'A':'T', 'C':'G', 'G':'C', 'T':'A',
    'R':'Y', 'Y':'R', 'S':'S', 'W':'W', 'K':'M', 'M':'K',
    'B':'V', 'V':'B', 'D':'H', 'H':'D', 'N':'N'}
print("".join(complement.get(base, base) for base in reversed(seq)).replace(" ", ""))